typography_spectrum: 0.5412186
color:
  saturation: 0
  brandStrength: 0.0674711475148797
  lightness: 1
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  rhythmicContrast: 0.8476703
layout_spectrum: 0.9641577
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf66807a-cc6c-4cbe-92f3-8910641b7f03.png
name: Hortelã Magenta
navigation:
  - name: portfólio
    id: 4db409af-a21f-4871-80ec-4d8ce963455f
    type: content
  - name: gráfico
    id: 5c2cc3f4-99b4-47ab-9f0d-a63cd01b9647
    type: content
  - name: editorial
    id: 3c05b7fa-500f-4f5c-bbe6-28779ccfb123
    type: content
  - name: trabalho 1
    id: 61af48d2-788e-4a61-b65a-edf0c35a2667
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Hortelã Magenta
description: design de comunicação
